In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



In [ ]:
data = pd.read_csv("gdrive/My Drive/Datasets/dataset_1.csv")
data

var_1  var_2  var_3  var_4  var_5  var_6  var_7  var_8  var_9  var_10  \
0          0      0    0.0   0.00    0.0      0      0      0      0       0   
1          0      0    0.0   3.00    0.0      0      0      0      0       0   
2          0      0    0.0   5.88    0.0      0      0      0      0       0   
3          0      0    0.0  14.10    0.0      0      0      0      0       0   
4          0      0    0.0   5.76    0.0      0      0      0      0       0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...     ...   
49995      0      0    0.0   2.85    0.0      0      0      0      0       0   
49996      0      0    0.0   2.91    0.0      0      0      0      0       0   
49997      0      0    0.0   8.46    0.0      0      0      0      0       0   
49998      0      0    0.0   2.76    0.0      0      0      0      0       0   
49999      0      0    0.0   5.64    0.0      0      0      0      0       0   

       ...  var_292  var_293  var_294  var_295  var_296  var_297  var_298  \
0      ...     0.00        0        0        0        0        0        0   
1      ...     0.00        0        0        0        0        0        0   
2      ...     0.00        0        0        3        0        0        0   
3      ...     0.00        0        0        0        0        0        0   
4      ...     0.00        0        0        0        0        0        0   
...    ...      ...      ...      ...      ...      ...      ...      ...   
49995  ...     0.00        0        0        0        0        0        0   
49996  ...     0.00        0        0        0        0        0        0   
49997  ...     0.00        0        0        0        0        0        0   
49998  ...     0.00        0        0        0        0        0        0   
49999  ...     2.85        0        0        0        0        0        0   

       var_299     var_300  target  
0          0.0      0.0000       0  
1          0.0      0.0000       0  
2          0.0  67772.7216       0  
3          0.0      0.0000       0  
4          0.0      0.0000       0  
...        ...         ...     ...  
49995      0.0      0.0000       0  
49996      0.0      0.0000       0  
49997      0.0      0.0000       0  
49998      0.0      0.0000       0  
49999      0.0      0.0000       0  

[50000 rows x 301 columns]

In [ ]:
data.columns

Index(['var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8',
       'var_9', 'var_10',
       ...
       'var_292', 'var_293', 'var_294', 'var_295', 'var_296', 'var_297',
       'var_298', 'var_299', 'var_300', 'target'],
      dtype='object', length=301)

In [ ]:
len(data.columns)

301

In [ ]:
X = data
array = np.array(X)
mean_array = np.mean(array,axis = 0)
print(X.shape,mean_array.shape)

(50000, 301) (301,)


In [ ]:
class varianceThreshold:
  def __init__(self,threshold=0.0):
    self.threshold = threshold
    self.inputFeatures = None
    variances_ = None
    self.selectedFeatures = None
    self.constant_features = None

  def fit(self,X,y=None):
    nexamples,nfeatures = X.shape
    self.inputFeatures = nfeatures
    self.array = np.array(X)
    mean_array = np.mean(array,axis = 0)
    mean_array = mean_array.reshape(1,mean_array.shape[0])
    difference = array - mean_array
    square_diff = difference ** 2
    sum_of_sqDiff = np.sum(square_diff,axis = 0)
    variances = sum_of_sqDiff/nexamples
    constant_features = np.where(variances <= self.threshold)[0]
    self.selectedFeatures = np.where(variances > self.threshold)[0]
    self._variances = variances
    self.constant_features = constant_features

  def get_support(self,indices=None):
    mask = self._variances > self.threshold
    return mask

  def get_columnsNames(self,columns):
    return columns[self.selectedFeatures]



  def transform(self):
    X = self.array[:,self.selectedFeatures]
    return  X







In [ ]:
selector = varianceThreshold()
selector.fit(X)


In [ ]:
print(selector._variances)

[1.16950716e-02 5.99964000e-05 1.63983148e+06 7.50807267e+00
 1.19929925e+08 3.99983992e+11 8.99910000e-04 1.04252198e-01
 7.19942400e-04 8.99967600e-04 9.13182495e+04 1.16975424e+03
 1.59134575e+06 1.99995996e+11 2.04939981e+00 5.05674792e+06
 9.75111753e+00 4.12792234e+06 9.84119640e-03 4.20992752e+01
 8.44537421e+07 3.85776998e+07 0.00000000e+00 8.77791600e-02
 9.54140400e-02 2.46445027e+04 1.40370813e+08 1.25991000e-03
 1.47860042e+09 2.15860217e+09 1.21017556e+00 8.63234544e-01
 0.00000000e+00 1.99995996e+11 3.82042839e+09 1.79996400e-04
 3.72824410e-01 3.27866828e-01 8.41921804e+06 1.39231117e+07
 9.41303245e+04 6.46357126e+06 9.19153600e-04 0.00000000e+00
 7.37507160e-03 3.41759330e+10 9.65772199e+08 4.80104131e+06
 2.24067643e+03 1.09149763e+02 1.76365440e-01 4.19180544e-02
 6.99510000e-04 1.00175856e-02 5.95361327e+07 2.05575640e-03
 8.40593472e+05 8.78906790e-01 8.45841240e-03 4.99749990e+12
 0.00000000e+00 1.28492869e+00 5.22897264e-02 6.27665697e+08
 8.80591903e+05 1.799964

In [ ]:
selector.selectedFeatures

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  61,  62,  63,  64,  65,  66,  67,  68,
        69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  81,  82,  83,
        84,  85,  87,  89,  90,  92,  93,  94,  95,  97,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 113, 114, 115, 116,
       117, 118, 120, 122, 123, 124, 125, 127, 128, 129, 130, 131, 132,
       133, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
       147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 158, 159, 160,
       161, 162, 163, 164, 165, 167, 168, 169, 171, 172, 173, 174, 175,
       176, 178, 180, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       192, 193, 196, 197, 198, 199, 201, 202, 203, 204, 205, 20

In [ ]:
selector.constant_features

array([ 22,  32,  43,  60,  79,  80,  86,  88,  91,  96,  98, 111, 112,
       119, 121, 126, 134, 157, 166, 170, 177, 179, 181, 194, 195, 200,
       211, 214, 224, 226, 247, 293, 296])

In [ ]:
col_names = selector.get_columnsNames(data.columns)

In [ ]:
X_selected = selector.transform()

In [ ]:
X_selected = pd.DataFrame(X_selected, columns=col_names)
X_selected

var_1  var_2  var_3  var_4  var_5  var_6  var_7  var_8  var_9  var_10  \
0        0.0    0.0    0.0   0.00    0.0    0.0    0.0    0.0    0.0     0.0   
1        0.0    0.0    0.0   3.00    0.0    0.0    0.0    0.0    0.0     0.0   
2        0.0    0.0    0.0   5.88    0.0    0.0    0.0    0.0    0.0     0.0   
3        0.0    0.0    0.0  14.10    0.0    0.0    0.0    0.0    0.0     0.0   
4        0.0    0.0    0.0   5.76    0.0    0.0    0.0    0.0    0.0     0.0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...     ...   
49995    0.0    0.0    0.0   2.85    0.0    0.0    0.0    0.0    0.0     0.0   
49996    0.0    0.0    0.0   2.91    0.0    0.0    0.0    0.0    0.0     0.0   
49997    0.0    0.0    0.0   8.46    0.0    0.0    0.0    0.0    0.0     0.0   
49998    0.0    0.0    0.0   2.76    0.0    0.0    0.0    0.0    0.0     0.0   
49999    0.0    0.0    0.0   5.64    0.0    0.0    0.0    0.0    0.0     0.0   

       ...  var_290  var_291  var_292  var_293  var_295  var_296  var_298  \
0      ...      0.0      0.0     0.00      0.0      0.0      0.0      0.0   
1      ...      0.0      0.0     0.00      0.0      0.0      0.0      0.0   
2      ...      0.0      0.0     0.00      0.0      3.0      0.0      0.0   
3      ...      0.0      0.0     0.00      0.0      0.0      0.0      0.0   
4      ...      0.0      0.0     0.00      0.0      0.0      0.0      0.0   
...    ...      ...      ...      ...      ...      ...      ...      ...   
49995  ...      0.0      0.0     0.00      0.0      0.0      0.0      0.0   
49996  ...      0.0      0.0     0.00      0.0      0.0      0.0      0.0   
49997  ...      0.0      0.0     0.00      0.0      0.0      0.0      0.0   
49998  ...      0.0      0.0     0.00      0.0      0.0      0.0      0.0   
49999  ...      0.0      0.0     2.85      0.0      0.0      0.0      0.0   

       var_299     var_300  target  
0          0.0      0.0000     0.0  
1          0.0      0.0000     0.0  
2          0.0  67772.7216     0.0  
3          0.0      0.0000     0.0  
4          0.0      0.0000     0.0  
...        ...         ...     ...  
49995      0.0      0.0000     0.0  
49996      0.0      0.0000     0.0  
49997      0.0      0.0000     0.0  
49998      0.0      0.0000     0.0  
49999      0.0      0.0000     0.0  

[50000 rows x 268 columns]

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold()
selector.fit(X)

# Get feature variances
print("\nFeature Variances:")
for name, var in zip(data.columns, selector.variances_):
    print(f"{name}: {var:.4f}")

col_names = selector.get_feature_names_out(data.columns)

#
X_selected = selector.transform(X)

# Convert back to DataFrame for visualization
df_selected = pd.DataFrame(X_selected, columns=col_names)
print("\nReduced Dataset Shape:", df_selected.shape)

# Display first few rows
df_selected.head()



Feature Variances:
var_1: 0.0117
var_2: 0.0001
var_3: 207901.3365
var_4: 7.5081
var_5: 445500.0000
var_6: 99999999.0000
var_7: 0.0009
var_8: 0.1043
var_9: 0.0007
var_10: 0.0009
var_11: 67511.0397
var_12: 1169.7542
var_13: 278597.6736
var_14: 99999999.0000
var_15: 2.0494
var_16: 377990.0850
var_17: 9.7511
var_18: 168147.5940
var_19: 0.0098
var_20: 42.0993
var_21: 596299.7988
var_22: 679174.2300
var_23: 0.0000
var_24: 0.0878
var_25: 0.0954
var_26: 10741.3629
var_27: 530000.6490
var_28: 0.0013
var_29: 1000227.0000
var_30: 2853976.3200
var_31: 1.2102
var_32: 0.8632
var_33: 0.0000
var_34: 99999999.0000
var_35: 3393413.2302
var_36: 0.0002
var_37: 0.3728
var_38: 0.3279
var_39: 262956.1572
var_40: 672382.4877
var_41: 11985.8679
var_42: 415159.0272
var_43: 0.0009
var_44: 0.0000
var_45: 0.0074
var_46: 21368791.0347
var_47: 450000.0000
var_48: 247701.5568
var_49: 99.0000
var_50: 109.1498
var_51: 0.1764
var_52: 0.0419
var_53: 0.0007
var_54: 0.0100
var_55: 528510.6729
var_56: 0.0021
var_57: 129789

var_1  var_2  var_3  var_4  var_5  var_6  var_7  var_8  var_9  var_10  ...  \
0    0.0    0.0    0.0   0.00    0.0    0.0    0.0    0.0    0.0     0.0  ...   
1    0.0    0.0    0.0   3.00    0.0    0.0    0.0    0.0    0.0     0.0  ...   
2    0.0    0.0    0.0   5.88    0.0    0.0    0.0    0.0    0.0     0.0  ...   
3    0.0    0.0    0.0  14.10    0.0    0.0    0.0    0.0    0.0     0.0  ...   
4    0.0    0.0    0.0   5.76    0.0    0.0    0.0    0.0    0.0     0.0  ...   

   var_290  var_291  var_292  var_293  var_295  var_296  var_298  var_299  \
0      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      0.0      0.0      0.0      3.0      0.0      0.0      0.0   
3      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

      var_300  target  
0      0.0000     0.0  
1      0.0000     0.0  
2  67772.7216     0.0  
3      0.0000     0.0  
4      0.0000     0.0  

[5 rows x 268 columns]

Feature Variances: [0.   0.25 0.  ]
Number of Input Features: 3
Selected Features Mask: [False  True False]
Selected Feature Indices: [1]
Selected Feature Names: ['B']
Reduced Dataset:
 [[0]
 [1]
 [0]
 [1]]
